[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "example03"
version = "0.1.0"
description = "A basic Python example."

[project.scripts]
api-server = "api:main.main"
